version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://user:pass@db/app
    depends_on:
      - db
      - redis

  db:
    image: postgres:14
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: securepassword

  redis:
    image: redis:6
    ports:
      - "6379:6379"

volumes:
  pgdata: